services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ledger
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  core-ledger:
    build: ./services/core-ledger
    environment:
      DATABASE_URL: mysql+pymysql://root:root@mysql:3306/ledger
    depends_on:
      mysql:
        condition: service_healthy

  pix-service:
    build: ./services/pix-service
    environment:
      LEDGER_URL: http://core-ledger:8001
      SYSTEM_PIX_PENDING_ACCOUNT: ${SYSTEM_PIX_PENDING_ACCOUNT}
      DEFAULT_MERCHANT_ACCOUNT: ${DEFAULT_MERCHANT_ACCOUNT}
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      PAGARME_SECRET_KEY: ${PAGARME_SECRET_KEY}
    depends_on:
      - core-ledger

  card-service:
    build: ./services/card-service
    environment:
      LEDGER_URL: http://core-ledger:8001
      SYSTEM_CARD_RECEIVABLE_ACCOUNT: ${SYSTEM_CARD_RECEIVABLE_ACCOUNT}
      DEFAULT_MERCHANT_ACCOUNT: ${DEFAULT_MERCHANT_ACCOUNT}
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      PAGARME_SECRET_KEY: ${PAGARME_SECRET_KEY}
    depends_on:
      - core-ledger

  crypto-service:
    build: ./services/crypto-service
    environment:
      LEDGER_URL: http://core-ledger:8001
      SYSTEM_CRYPTO_PENDING_ACCOUNT: ${SYSTEM_CRYPTO_PENDING_ACCOUNT}
      DEFAULT_MERCHANT_ACCOUNT: ${DEFAULT_MERCHANT_ACCOUNT}
      HD_WALLET_MNEMONIC: ${HD_WALLET_MNEMONIC}
      WEB3_RPC_URL: ${WEB3_RPC_URL:-https://polygon-rpc.com}
      MATIC_BRL_RATE: ${MATIC_BRL_RATE:-2.50}
      USDT_BRL_RATE: ${USDT_BRL_RATE:-5.50}
    volumes:
      - cryptodata:/app/data
    depends_on:
      - core-ledger

  admin-panel:
    build: ./services/admin-panel
    environment:
      LEDGER_URL: http://core-ledger:8001
      PIX_URL: http://pix-service:8002
      CARD_URL: http://card-service:8003
      CRYPTO_URL: http://crypto-service:8004
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      ADMIN_PANEL_SECRET: ${ADMIN_PANEL_SECRET:-troque-isto}
    depends_on:
      - core-ledger
      - pix-service


  customer-portal:
    build: ./services/customer-portal
    environment:
      LEDGER_URL: http://core-ledger:8001
      CUSTOMER_PORTAL_SECRET: ${CUSTOMER_PORTAL_SECRET:-troque-isto}
    depends_on:
      - core-ledger

volumes:
  mysqldata:
  cryptodata:
